export const wikibaseWorldPropertySchema = [
    ['URL', 'url'],
    ['host', 'wikibase-item'],
    ['instance of', 'wikibase-item'],
    ['exact match', 'url'],
    ['inception date', 'time'],
    ['logo on Wikimedia Commons', 'commonsMedia'],
    ['query service UI', 'url'],
    ['query service SPARQL endpoint URL', 'url'],
    ['license or copyright status', 'wikibase-item'],
    ['bug tracker (project-specific)', 'url'],
    ['Reserved property slot P11', 'string'],
    ['supported entity types', 'wikibase-item'],
    ['availability status', 'wikibase-item'],
    ['MediaWiki extension in use', 'wikibase-item'],
    ['WikiApiary wiki ID', 'external-id'],
    ['formatter URL', 'string'],
    ['author', 'wikibase-item'],
    ['supports application', 'wikibase-item'],
    ['applies to namespace', 'wikibase-item'],
    ['gadget installed', 'wikibase-item'],
    ['reference URL', 'url'],
    ['reference date', 'time'],
    ['version identifier', 'string'],
    ['has quality', 'wikibase-item'],
    ['comment', 'string'],
    ['participant', 'wikibase-item'],
    ['subclass of', 'wikibase-item'],
    ['discontinued date', 'time'],
    ['uses', 'wikibase-item'],
    ['of', 'wikibase-item'],
    ['replaces', 'wikibase-item'],
    ['replaced by', 'wikibase-item'],
    ['required feature', 'wikibase-item'],
    ['series ordinal', 'string'],
    ['archive URL', 'url'],
    ['Wikidata entity identifier', 'external-id'],
    ['wiki tool used', 'wikibase-item'],
    ['service entry date', 'time'],
    ['Reserved property slot P39', 'string'],
    ['Reserved property slot P40', 'string'],
    ['Reserved property slot P41', 'string'],
    ['Reserved property slot P42', 'string'],
    ['Reserved property slot P43', 'string'],
    ['WikiIndex page', 'wikibase-property'],
    ['has part', 'wikibase-item'],
    ['Wikimedia Commons category', 'string'],
    ['different from', 'wikibase-item'],
    ['publisher', 'wikibase-item'],
    ['wiki main page URL', 'url'],
    ['as of', 'time'],
    ['MediaWiki.org identifier', 'external-id'],
    ['Reserved property slot P52', 'string'],
    ['wikibase-metadata.toolforge.org ID', 'external-id'],
    ['wikibase.cloud numeric ID', 'external-id'],
    ['links to Wikibase', 'wikibase-item'],
    ['linked from Wikibase', 'wikibase-item'],
    ['MediaWiki version', 'string'],
    ['property count', 'quantity'],
    ['edit count', 'quantity'],
    ['user count', 'quantity'],
    ['active user count', 'quantity'],
    ['page count', 'quantity'],
    ['reference quote', 'monolingualtext'],
    ['Wikibase usage', 'monolingualtext'],
    ['example item', 'url'],
    ['described at URL', 'url'],
    ['highest item ID', 'quantity'],
    ['PHP Version', 'string'],
    ['MediaWiki DB Type', 'string'],
    ['MediaWiki DB Version', 'string'],
    ['Reserved property slot P71', 'string'],
    ['Reserved property slot P72', 'string'],
    ['Month of last edit', 'time'],
] as const;
